language: c
dist: trusty
before_install:
  - sudo apt-get update -qq
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
install:
  - sudo apt-get install libcap-dev -qq
  - sudo apt-get install nettle-dev -qq

compiler:
  - gcc
  - clang
env:
  global:
   - secure: "JjKYmA31tVdP2j7HaRwndcLGJe8vWruxPSilU/qWZe60WF3qP36VcTXrq7KGOKr90KkQIQDn7t25OsKs+XieZu2RjNU9wRGi0zOV5o5KaMc2OYeviLZ95gKegAHCZcq/v/IDSUAf6JerJTCDd26rDlsvFZNPCh2ilTDBdKjHVag=<Paste>"
  matrix:
    - USE_CAP=true
    - USE_CAP=false
    - USE_IDN=true
    - USE_IDN=false
addons:
  coverity_scan:
    project:
      name: "iputils/iputils"
      description: "The iputils package is set of small useful utilities for Linux networking."
    notification_email: david@ixit.cz
    build_command: "make"
    branch_pattern: coverity_scan

script:
  - make
